### ISSUE TITLE
ActiveRecord 3.2 doesn't have ConnectionAdapters::Column.value_to_date

### ISSUE THREAD

**Issue by orangethunder** [devmynd/hstore_accessor#49]
The gem specifies that it works with ActiveRecord 3.2 and higher.  However, the above method only seems to be available from ActiveRecord 4.0.  So attributes of type date don't work.  I hope I am missing something, otherwise it may be a good idea to drop 3.2 support or use the string_to_date method when ActiveRecord 3.2 is in use.

**Comment by crismali** [comment]
Could you provide a bit more context around how you're seeing this error? Specifically the ActiveRecord version, Hstore Accessor version, the error you're seeing, and code that produces the error. 

Also, could you provide a link to where the project specifies Rails 3.2 support? I see on RubyGems it specifies a dependency on ActiveSupport 3.2, but nothing about ActiveRecord 3.2. 

There will be a new release soon that will either support ActiveRecord 4.0 and up, or possibly just ActiveRecord 4.2 and up.

**Comment by lefty313** [comment]
> There will be a new release soon that will either support ActiveRecord 4.0 and up, or possibly just ActiveRecord 4.2 and up.

:+1:

**Comment by crismali** [comment]
@lefty313, just released the new versions =)
