### ISSUE TITLE
Support for rails 4.2

### ISSUE THREAD

**Issue by lefty313** [devmynd/hstore_accessor#54]
Hi 

I tried to use gem with rails 4.2  but it doesn't work because it have different
typecasting inferface

https://github.com/devmynd/hstore_accessor/blob/89871d834cb68b6dc21aac9255a84d3258daa813/lib/hstore_accessor/type_helpers.rb#L56-L73

methods used here doesn't exist anymore.

Here is short description what exactly changed in latest release 

http://metaskills.net/2015/01/06/activerecord-42s-type-casting/

--

Do you want to support that feature ? I could try to prepare pr but I need your opinion first

**Comment by crismali** [comment]
@lefty313, the new release will be up soon, we just need to make sure there won't be any changes to serialization (#53) so that way we don't have to have another major release right away

**Comment by eprothro** [comment]
FWIW, I'd recommend merging #52 before releasing, as current HEAD breaks dirty tracking.

**Comment by crismali** [comment]
I'll check out #52 soon
