### ISSUE TITLE
Why have arrays been removed and recommended alternatives

### ISSUE THREAD

**Issue by jeffblake** [devmynd/hstore_accessor#57]
Hi,

I use arrays pretty extensively for tagging IDs of associated records. hstore_accessor worked great for this. Why has it been removed and what should we be doing instead? Thanks.

**Comment by crismali** [comment]
It's removed in version 1.0.0 but 0.9.0 still supports them with Rails 4.2 support and some other features as well. 

We had a lot of internal discussion about this and considered a lot of different options. The biggest problem was figuring out the best way to serialize arrays and hashes (JSON? YAML? etc) and we concluded that that ultimately depends on the use case to the point where there wasn't really a correct default behavior. 

There are several options if you still want arrays and hashes though. You could use Rails' built in `[serialize](http://api.rubyonrails.org/classes/ActiveRecord/Base.html)` method to serialize arrays or hashes to a column (You might be able to declare a string typed hstore accessor field and serialize into that if you want to keep it in your hstore column). You could also add array or hstore columns to the model in question. 

Hope that helps!

**Comment by thegrubbsian** [comment]
I think one way we could potentially add this support back in (sort of) would be to provide a standard serialization plugin scheme.  Perhaps allowing you to specify a proc or a serialization class when you define a field of type :hash or :array.  This would allow people to choose what serialization/deserialization method should be used when persisting or fetching the hstore values from the DB but it would keep that logic out of the core gem itself.

**Comment by jeffblake** [comment]
Or maybe keeping it very simple and explicitly supporting only arrays of integers. It's very useful functionality and removes the need for join tables in simple use-cases (of which I'd imagine is 95% of scenarios)

**Comment by sidfarkus** [comment]
Adding my support for adding arrays/hashes back in.  We have simple arrays of strings in hstore we don't query but I'd like to keep them arrays without having to write more code to handle them.  The 0.9.0 version works great here; I think using YAML as the default with an option to specify the serializer class (any class with `.dump` and `.load`) would be great.

**Comment by jhirn** [comment]
One of the leading factors behind the decision to remove array and object types is that they are not supported by Postgres. They cannot be treated as anything more than a string, nor can they be indexed or first class citizens. 


The intent of the gem is to support features provided by Postgres, not extend them. I can't recommend using hstore for this type of data but if you must you should just create a string type column and serialize using whatever's best for your needs.
