### ISSUE TITLE
default values

### ISSUE THREAD

**Issue by kirillsalykin** [devmynd/hstore_accessor#7]
it should be possible to add default value, like 
hstore_accessor :settings, share_via_facebook: :boolean, default: false

**Comment by cjjuice** [comment]
+1 sitting on 193 keys 95% are strings lol

**Comment by mockdeep** [comment]
A default would be great. I could see setting it in the database, especially for boolean values. We have some that default to `true`, which means we make `column_name != false` comparisons in our code. This also has implications for the query methods:

```irb
> Product.is_popular
=> []
> Product.not_popular
=> []
> Product.count
=> 52
```
